version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: lab-website
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production-12345
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./prisma:/app/prisma
      - ./db:/app/db
    restart: unless-stopped
    networks:
      - lab-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  lab-network:
    driver: bridge